### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by abc123me** [Discord4J/discord4j-web#9]
None of the download links on your website are operational:
https://ci.discord4j.com/downloads.html

**Comment by darichey** [comment]
Hi, that is actually our old website which should not be used anymore (in fact, I'm very surprised it's still up). You should use https://discord4j.com/ and the instructions at https://docs.discord4j.com/quickstart#download--installation to use Gradle/Maven to manage downloading the library.

**Comment by abc123me** [comment]
OK, Would you mind helping me with something else then?

I'm trying to implement discord4j in a Minecraft mod and need a copy of the shaded JAR to do so which isn't available on the new website. Is there a way I can generate that with gradle or something else?
